// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.sep3yg9.njorddata.grpc.protobuf.user;

public interface SearchingUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sep3yg9.njorddata.grpc.protobuf.user.SearchingUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string email = 2;</code>
   */
  String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string fullName = 3;</code>
   */
  String getFullName();
  /**
   * <code>string fullName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
