// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.sep3yg9.njorddata.grpc.protobuf.user;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sep3yg9.njorddata.grpc.protobuf.user.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sep3yg9.njorddata.grpc.protobuf.user.User user = 1;</code>
   */
  java.util.List<User>
      getUserList();
  /**
   * <code>repeated .com.sep3yg9.njorddata.grpc.protobuf.user.User user = 1;</code>
   */
  User getUser(int index);
  /**
   * <code>repeated .com.sep3yg9.njorddata.grpc.protobuf.user.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .com.sep3yg9.njorddata.grpc.protobuf.user.User user = 1;</code>
   */
  java.util.List<? extends UserOrBuilder>
      getUserOrBuilderList();
  /**
   * <code>repeated .com.sep3yg9.njorddata.grpc.protobuf.user.User user = 1;</code>
   */
  UserOrBuilder getUserOrBuilder(
      int index);
}
