// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.sep3yg9.njorddata.grpc.protobuf.user;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_CreatingUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_CreatingUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UpdatingUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UpdatingUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_SearchingUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_SearchingUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_BasicUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_BasicUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UserList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021UserService.proto\022(com.sep3yg9.njordda" +
      "ta.grpc.protobuf.user\032\033google/protobuf/e" +
      "mpty.proto\032\036google/protobuf/wrappers.pro" +
      "to\"S\n\014CreatingUser\022\020\n\010fullName\030\001 \001(\t\022\020\n\010" +
      "userName\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010passwor" +
      "d\030\004 \001(\t\"M\n\014UpdatingUser\022\n\n\002id\030\001 \001(\005\022\020\n\010u" +
      "serName\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010password" +
      "\030\004 \001(\t\"B\n\rSearchingUser\022\020\n\010userName\030\001 \001(" +
      "\t\022\r\n\005email\030\002 \001(\t\022\020\n\010fullName\030\003 \001(\t\">\n\tBa" +
      "sicUser\022\020\n\010fullName\030\001 \001(\t\022\020\n\010userName\030\002 ",
      "\001(\t\022\r\n\005email\030\003 \001(\t\"W\n\004User\022\n\n\002id\030\001 \001(\005\022\020" +
      "\n\010fullName\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010userN" +
      "ame\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\"H\n\010UserList\022" +
      "<\n\004user\030\001 \003(\0132..com.sep3yg9.njorddata.gr" +
      "pc.protobuf.user.User2\323\004\n\013UserService\022t\n" +
      "\nCreateUser\0226.com.sep3yg9.njorddata.grpc" +
      ".protobuf.user.CreatingUser\032..com.sep3yg" +
      "9.njorddata.grpc.protobuf.user.User\022\\\n\nU" +
      "pdateUser\0226.com.sep3yg9.njorddata.grpc.p" +
      "rotobuf.user.UpdatingUser\032\026.google.proto",
      "buf.Empty\022A\n\nDeleteUser\022\033.google.protobu" +
      "f.Int32Value\032\026.google.protobuf.Empty\022Z\n\n" +
      "GetByEmail\022\034.google.protobuf.StringValue" +
      "\032..com.sep3yg9.njorddata.grpc.protobuf.u" +
      "ser.User\022V\n\007GetById\022\033.google.protobuf.In" +
      "t32Value\032..com.sep3yg9.njorddata.grpc.pr" +
      "otobuf.user.User\022y\n\nSearchUser\0227.com.sep" +
      "3yg9.njorddata.grpc.protobuf.user.Search" +
      "ingUser\0322.com.sep3yg9.njorddata.grpc.pro" +
      "tobuf.user.UserListB\023P\001\252\002\016GRPCUserClient",
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_CreatingUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_CreatingUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_CreatingUser_descriptor,
        new String[] { "FullName", "UserName", "Email", "Password", });
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UpdatingUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UpdatingUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UpdatingUser_descriptor,
        new String[] { "Id", "UserName", "Email", "Password", });
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_SearchingUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_SearchingUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_SearchingUser_descriptor,
        new String[] { "UserName", "Email", "FullName", });
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_BasicUser_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_BasicUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_BasicUser_descriptor,
        new String[] { "FullName", "UserName", "Email", });
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_User_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_User_descriptor,
        new String[] { "Id", "FullName", "Email", "UserName", "Password", });
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UserList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sep3yg9_njorddata_grpc_protobuf_user_UserList_descriptor,
        new String[] { "User", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
