// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.sep3yg9.njorddata.grpc.protobuf.user;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sep3yg9.njorddata.grpc.protobuf.user.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string fullName = 2;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string userName = 4;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 5;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 5;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
